[package]
authors = ["Supanat Potiwarakorn <boss@osmosis.team>", "Justin Kilpatrick <justin@althea.net>", "Tony Arcieri <tony@iqlusion.io>"]
edition = "2021"
name = "proto-build"
publish = false
version = "0.1.0"

[dependencies]
heck = "0.4.0"
itertools = "0.10.3"
log = "0.4.17"
pretty_env_logger = "0.4.0"
prettyplease = "0.1.16"
prost = "0.11.0"
prost-build = "0.11.1"
prost-types = "0.11.1"
regex = "1"
syn = {version = "1.0.98", features = ["full", "parsing"]}
tonic = "0.8.1"
tonic-build = "0.8.0"
walkdir = "2"
